### ISSUE TITLE
What is the Chinese word at line 206 in tokenizer.java ?

### ISSUE THREAD

**Issue by StevenLOL** [PKULCWM/PKUSUMSUM#5]
[https://github.com/PKULCWM/PKUSUMSUM/blob/master/code/Tokenizer.java#L206](https://github.com/PKULCWM/PKUSUMSUM/blob/master/code/Tokenizer.java#L206)

**Comment by StevenLOL** [comment]
Wait.. it's not a Chinese word , it's an expression.

**Comment by qingniufly** [comment]
What the expression means？Some punctuation？
Seems like delimiters for sentences
