### ISSUE TITLE
Tokenize Chinese Sentence Problem

### ISSUE THREAD

**Issue by stevenzhang027** [PKULCWM/PKUSUMSUM#9]
`Pattern pattern = Pattern.compile(".*?[¡££¿£¡]");`

Hi, I encountered a problem integrating PKUSUMSUM source code into my project, the tokenizer did not work well because of the above code in **PKUSUMSUM/code/Tokenizer.java line 183**. I suppose it is utilized to match Chinese sentences.

Could anyone please explain how this pattern works?

**Comment by PKULCWM** [comment]
It supposed to  Pattern pattern =Pattern.compile(".*?[。？！]")
It might be some encoding error when uploading the  source code. We have tried many times but it still didn't work. Sorry for the problem.

**Comment by leisurehippo** [comment]
how to solve
